# Generated by Django 4.1.2 on 2023-02-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0005_live_data_delete_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_details',
            name='student_id',
        ),
        migrations.AddField(
            model_name='attendance_details',
            name='usn',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='live_data',
            name='Datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
