# Generated by Django 4.1.2 on 2023-05-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0008_rename_attendence_time_attendance_details_attendence_timedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_details',
            old_name='attendence_timedate',
            new_name='attendence_time',
        ),
    ]
